apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: muno
  namespace: muno
  labels:
    app.kubernetes.io/name: muno
    app.kubernetes.io/part-of: noetl
spec:
  domains:
    - muno.mestumre.dev
