---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: object-store-seaweedfs
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/object-store-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-store-data
  namespace: object-store
spec:
  volumeName: object-store-seaweedfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
