{{- if .Values.objectStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: object-store-credentials
  namespace: {{ .Values.objectStore.namespace }}
  labels:
    app: object-store
    object-store.noetl.io/backend: {{ .Values.objectStore.kind | quote }}
type: Opaque
data:
  access-key: {{ .Values.objectStore.credentials.accessKey | b64enc }}
  secret-key: {{ .Values.objectStore.credentials.secretKey | b64enc }}
{{- end }}
