
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: UkVQTEFDRV9NRV9MT0NBTF9ERVZfT05MWQ==  # 'demo' encoded in base64
  NOETL_PASSWORD: UkVQTEFDRV9NRV9MT0NBTF9ERVZfT05MWQ==     # 'noetl' encoded in base64
